### PR TITLE
hlsl cs codegen

### PR DESCRIPTION
**Pull request by xiayuqing0622**
To generate c# code for hlsl backend, users need to add flag -fhlsl_csharp_codegen.

### CODE REVIEW

**Comment by xysmlx** [comment]
The modification of depthwise convolution works well in the NASNet model.
However, the unit-test of the depthwise con2d op failed.
```
[ RUN      ] nnfusion_core_kernels.depthwise_conv2d
/tmp/fileWHTmJh.cu(67) Error: unsupported operation

[ERROR] 2020-12-08T09:33:42z src/nnfusion/engine/profiler/profiler.hpp 145      Failed execute the kernel.
[INFO] 2020-12-08T09:33:42z test/nnfusion/kernels/../test_util/common.hpp 100   Kernel empty result.
xxxxxx/nnfusion/test/nnfusion/kernels/depthwise_conv2d.cpp:73: Failure
Value of: nnfusion::test::check_kernel<float>(gnode, CUDA_GPU, IN, OUT)
  Actual: false
Expected: true
[  FAILED  ] nnfusion_core_kernels.depthwise_conv2d (355 ms)
```

**Comment by xiayuqing0622** [comment]
> nnfusion_core_kernels.depthwise_conv2d

just updated

**Comment by xiayuqing0622** [comment]
> Hi, @xiayuqing0622 , the modification of depthwise convolution works well in the NASNet model end-to-end test.
> However, the unit-test of the depthwise con2d op failed.
> 
> ```
> [ RUN      ] nnfusion_core_kernels.depthwise_conv2d
> /tmp/fileWHTmJh.cu(67) Error: unsupported operation
> 
> [ERROR] 2020-12-08T09:33:42z src/nnfusion/engine/profiler/profiler.hpp 145      Failed execute the kernel.
> [INFO] 2020-12-08T09:33:42z test/nnfusion/kernels/../test_util/common.hpp 100   Kernel empty result.
> xxxxxx/nnfusion/test/nnfusion/kernels/depthwise_conv2d.cpp:73: Failure
> Value of: nnfusion::test::check_kernel<float>(gnode, CUDA_GPU, IN, OUT)
>   Actual: false
> Expected: true
> [  FAILED  ] nnfusion_core_kernels.depthwise_conv2d (355 ms)
> ```

@xysmlx  just updated

**Comment by xysmlx** [comment]
> > Hi, @xiayuqing0622 , the modification of depthwise convolution works well in the NASNet model end-to-end test.
> > However, the unit-test of the depthwise con2d op failed.
> > ```
> > [ RUN      ] nnfusion_core_kernels.depthwise_conv2d
> > /tmp/fileWHTmJh.cu(67) Error: unsupported operation
> > 
> > [ERROR] 2020-12-08T09:33:42z src/nnfusion/engine/profiler/profiler.hpp 145      Failed execute the kernel.
> > [INFO] 2020-12-08T09:33:42z test/nnfusion/kernels/../test_util/common.hpp 100   Kernel empty result.
> > xxxxxx/nnfusion/test/nnfusion/kernels/depthwise_conv2d.cpp:73: Failure
> > Value of: nnfusion::test::check_kernel<float>(gnode, CUDA_GPU, IN, OUT)
> >   Actual: false
> > Expected: true
> > [  FAILED  ] nnfusion_core_kernels.depthwise_conv2d (355 ms)
> > ```
> 
> @xysmlx just updated

@xiayuqing0622 Both NASNet end-to-end test and the unit-test of the depthwise con2d op have passed. The modification of the depthwise conv2d op has been reviewed. Great!

**Comment by xysmlx** [comment]
> > > Hi, @xiayuqing0622 , the modification of depthwise convolution works well in the NASNet model end-to-end test.
> > > However, the unit-test of the depthwise con2d op failed.
> > > ```
> > > [ RUN      ] nnfusion_core_kernels.depthwise_conv2d
> > > /tmp/fileWHTmJh.cu(67) Error: unsupported operation
> > > 
> > > [ERROR] 2020-12-08T09:33:42z src/nnfusion/engine/profiler/profiler.hpp 145      Failed execute the kernel.
> > > [INFO] 2020-12-08T09:33:42z test/nnfusion/kernels/../test_util/common.hpp 100   Kernel empty result.
> > > xxxxxx/nnfusion/test/nnfusion/kernels/depthwise_conv2d.cpp:73: Failure
> > > Value of: nnfusion::test::check_kernel<float>(gnode, CUDA_GPU, IN, OUT)
> > >   Actual: false
> > > Expected: true
> > > [  FAILED  ] nnfusion_core_kernels.depthwise_conv2d (355 ms)
> > > ```
> > 
> > 
> > @xysmlx just updated
> 
> @xiayuqing0622 Both NASNet end-to-end test and the unit-test of the depthwise con2d op have passed. However, the unit-test of nnfusion_tensorflow_import.depthwise_conv2d_op failed due to segfault.
> 
> ```
> [ RUN      ] nnfusion_tensorflow_import.depthwise_conv2d_op
> [INFO] 2020-12-09T06:12:29z src/nnfusion/frontend/tensorflow_import/tensorflow.cpp 18   Import Tensorflow Graph Size: [311]
> [INFO] 2020-12-09T06:12:29z src/nnfusion/frontend/tensorflow_import/util/graph_convert.cpp 3422 Converting Tensorflow Graph
> [INFO] 2020-12-09T06:12:29z src/nnfusion/frontend/tensorflow_import/util/graph_convert.cpp 3514 convert graph done
> [ERROR] 2020-12-09T06:12:29z src/nnfusion/engine/profiler/profiling_runtime.hpp 530     No valid Profiling Context for this node : Reshape_1154 (op type : Reshape).
> Segmentation fault (core dumped)
> ```

@xiayuqing0622 All the tests of the depthwise con2d op have passed. The modification of the depthwise conv2d op has been reviewed.

**Review by jlxue — APPROVED** [review]

**Pull request merged**
