### PR TITLE
[Typo] An automatic github action solution for typo inspection.

### PR DESCRIPTION
**Pull request by LeiWang1999**
# An automatic github action solution for typo inspection.

## Description

Refer to this [comment](https://github.com/microsoft/nnfusion/pull/414#issuecomment-1094770432), inspection for spelling is a trouble work, this pr gives a github action solution.

This pull request takes insight from microsoft terminal repo, issue [4473](https://github.com/microsoft/terminal/issues/4473), github action [check-spelling](https://github.com/check-spelling/check-spelling), we use the latest released version 0.0.19(the same version used in microsoft terminal).

And a macos .DS_Store gitignore addition.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I made a private repository to test the github action workload, check-spelling will work on both stage of pull request and push.

## Future work

- [x] Perfect the white list (non-breaking change which adds functionality)
some domain-specified whitelist words (for example, `protobuf`、 `ONNX` or contributors' names like `LeiWang1999`) should be appended into the `.github/actions/allow/allow.txt` or `.github/actions/allow/*.txt` (all files in allow directory will be merged) when processing.

I created a bit of white list to cover some simple words, for example, `nnfusion`, `microsoft`.etc . But it's quite a dirty work! The unrecognized words in nnfusion is not a little (the dictionary will have about 1000 words? I guess),  maybe we need some volunteers to cover this work.

### CODE REVIEW

**Comment by LeiWang1999** [comment]
Test pull request and currently un unrecognized words can be reviewed at [intentional typo](https://github.com/LeiWang1999/nnfusion/pull/2).

words' location can be found at action [runs](https://github.com/LeiWang1999/nnfusion/runs/5974838385?check_suite_focus=true)

**Comment by LeiWang1999** [comment]
Please CC @wenxcs

**Comment by LeiWang1999** [comment]
Now I had tried my best to fix the typo of nnfusion, a lot of words are append to the whitelist and a lot of words are fixed. The Github Action bot can work well. It's tested in this [pr](https://github.com/LeiWang1999/nnfusion/pull/4).

Please CC @wenxcs

**Review by wenxcs — APPROVED** [review]

**Pull request merged**
