### PR TITLE
Refactor BlockFusion

### PR DESCRIPTION
**Pull request by xysmlx**
* Remove the following passes in rammer artifact breakdown evaluation: rammer_base_k and rammer_fast
* Refactor BlockFusion

### CODE REVIEW

**Review by wenxcs — COMMENTED** [review]
Reviewed

**Review by wenxcs — DISMISSED** [review]
Re-reviewed

**Comment by wenxcs** [comment]
Failed in code style check.

**Comment by xysmlx** [comment]
> Failed in code style check.

The code style problem has been fixed and it has passed the pipeline check.

**Review by wenxcs — APPROVED** [review]

**Pull request merged**
