### PR TITLE
Add sigmoid autodiff

### PR DESCRIPTION
**Pull request by siahuat0727**
Passed unit test

### CODE REVIEW

**Review by xysmlx — APPROVED** [review]

**Comment by xysmlx** [comment]
Hi @siahuat0727 , the pipeline shows "Code style check failed. Please using apply_code_style.sh to apply code style". Please use maint/script/apply_code_style.sh to format this code.

**Comment by siahuat0727** [comment]
Done.
Sorry for not noticing the instructions. @xysmlx

**Review by xysmlx — APPROVED** [review]

**Pull request merged**
