### PR TITLE
two constant fixed

### PR DESCRIPTION
**Pull request by Niupple**
Fixed the problem where the program would generate two identical "Constant" directories, by changing the 'cp' command to 'mv' command.

### CODE REVIEW

**Review by wenxcs — APPROVED** [review]

**Comment by wenxcs** [comment]
Maybe there is another problem: two param.json files.

**Review by xiayuqing0622 — DISMISSED** [review]

**Comment by xiayuqing0622** [comment]
> Maybe there is another problem: two param.json files.

there's only one para_info.json file, and it is in build folder. Since this file is for our training tool, we can add a flag to indicate whether to generate this file or not.

**Comment by Niupple** [comment]
Moved the para_info.json file to the same directory as main_test.cpp now.

**Review by wenxcs — APPROVED** [review]

**Pull request merged**
